insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (1, 'Safety Officer', 19, 14, 47);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (2, 'Pipelayer', 37, 12, 11);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (3, 'Concrete Finisher', 46, 31, 31);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (4, 'Glazier', 49, 44, 41);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (5, 'Safety Officer', 18, 7, 48);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (6, 'Plasterers', 37, 35, 5);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (7, 'Plumber', 5, 49, 23);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (8, 'Pipefitter', 13, 7, 33);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (9, 'Brickmason', 24, 44, 13);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (10, 'Stucco Mason', 50, 7, 24);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (11, 'Waterproofer', 28, 2, 50);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (12, 'Brickmason', 11, 23, 41);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (13, 'Millwright', 18, 24, 23);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (14, 'Boilermaker', 48, 13, 50);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (15, 'Welder', 40, 28, 25);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (16, 'Cement Mason', 41, 25, 2);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (17, 'Waterproofer', 49, 6, 30);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (18, 'Stucco Mason', 50, 9, 33);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (19, 'Glazier', 13, 18, 5);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (20, 'Pipelayer', 8, 7, 9);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (21, 'HVAC', 15, 15, 10);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (22, 'Welder', 6, 35, 4);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (23, 'Electrician', 49, 45, 22);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (24, 'Brickmason', 40, 34, 40);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (25, 'Brickmason', 12, 30, 36);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (26, 'Waterproofer', 4, 18, 1);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (27, 'Welder', 5, 32, 16);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (28, 'Plumber', 22, 27, 12);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (29, 'Painter', 41, 29, 50);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (30, 'Laborer', 7, 41, 19);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (31, 'Carpenter', 14, 21, 32);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (32, 'Electrician', 14, 39, 50);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (33, 'Welder', 24, 48, 21);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (34, 'Sheet Metal Worker', 48, 41, 43);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (35, 'Carpenter', 33, 49, 2);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (36, 'Refridgeration', 14, 24, 26);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (37, 'Laborer', 17, 2, 49);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (38, 'Boilermaker', 36, 37, 23);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (39, 'Refridgeration', 11, 44, 25);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (40, 'Sheet Metal Worker', 4, 47, 4);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (41, 'Millwright', 16, 16, 11);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (42, 'Painter', 6, 21, 21);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (43, 'Waterproofer', 27, 44, 34);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (44, 'Laborer', 2, 46, 43);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (45, 'Plumber', 34, 42, 6);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (46, 'Landscaper', 39, 18, 13);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (47, 'Pipelayer', 25, 11, 46);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (48, 'Millwright', 27, 23, 6);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (49, 'Linemen', 13, 36, 20);
insert into athletes (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (50, 'Cement Mason', 15, 25, 26);