insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (1, 'Sheet Metal Worker', 37, 39, 40);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (2, 'Concrete Finisher', 27, 43, 33);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (3, 'Stucco Mason', 20, 40, 10);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (4, 'Equipment Operator', 6, 41, 24);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (5, 'Carpenter', 27, 5, 17);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (6, 'Landscaper', 23, 34, 49);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (7, 'Linemen', 20, 5, 19);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (8, 'HVAC', 50, 10, 11);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (9, 'Pipelayer', 17, 38, 45);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (10, 'Sheet Metal Worker', 38, 42, 43);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (11, 'HVAC', 2, 29, 13);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (12, 'Plasterers', 17, 24, 44);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (13, 'Sheet Metal Worker', 4, 13, 17);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (14, 'Carpenter', 29, 32, 41);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (15, 'Sheet Metal Worker', 29, 35, 11);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (16, 'Plasterers', 10, 13, 49);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (17, 'Refridgeration', 3, 9, 40);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (18, 'Stucco Mason', 30, 45, 5);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (19, 'Landscaper', 33, 30, 13);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (20, 'Landscaper', 17, 44, 41);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (21, 'Stucco Mason', 39, 39, 14);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (22, 'Plasterers', 32, 33, 23);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (23, 'Ironworker', 6, 36, 21);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (24, 'Carpenter', 38, 13, 7);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (25, 'Tile Setter', 9, 37, 9);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (26, 'Plumber', 38, 7, 10);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (27, 'Concrete Finisher', 34, 47, 9);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (28, 'Cement Mason', 40, 21, 45);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (29, 'Concrete Finisher', 16, 6, 39);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (30, 'Ironworker', 4, 1, 31);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (31, 'Millwright', 24, 46, 30);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (32, 'Carpenter', 30, 36, 12);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (33, 'Terrazzo', 40, 47, 6);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (34, 'Plumber', 6, 9, 16);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (35, 'Ironworker', 1, 18, 46);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (36, 'Boilermaker', 25, 3, 15);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (37, 'Terrazzo', 5, 37, 41);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (38, 'Waterproofer', 30, 3, 50);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (39, 'Equipment Operator', 42, 1, 38);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (40, 'Equipment Operator', 38, 31, 41);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (41, 'Waterproofer', 22, 16, 41);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (42, 'Electrician', 49, 46, 17);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (43, 'Carpenter', 48, 6, 14);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (44, 'Safety Officer', 35, 41, 43);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (45, 'Plasterers', 15, 4, 25);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (46, 'Refridgeration', 2, 44, 23);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (47, 'Pipefitter', 11, 14, 10);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (48, 'Safety Officer', 1, 22, 43);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (49, 'Terrazzo', 11, 21, 17);
insert into events (EventsID, EventName, WinnerGold, WinnerSilver, WinnerBronze) values (50, 'Cement Mason', 27, 49, 12);
